export const projects = [
  {
    id: 1,
    title: "Moragea",
    description: "Full-featured shopping app with cart, payments, and order tracking. Built with Flutter and Firebase.",
    image: "/moragea/cover_imag.webp",
    gallery: [
      "/moragea/m1.webp",
      "/moragea/m2.webp",
      "/moragea/m3.webp",
      "/moragea/m4.webp",
      "/moragea/m5.webp",
      "/moragea/m6.webp",
      "/moragea/m7.webp",
      "/moragea/m8.webp",
      "/moragea/m9.webp",
    ],
    tags: ["Flutter", "Firebase", "Stripe", "Provider"],
    github: "https://github.com",
    demo: "https://demo.com",
  },
  {
    id: 2,
    title: "Night Dream",
    description: "Track workouts, monitor progress, and achieve fitness goals. Features custom animations and charts.",
    image: "/night-dream/cover.webp",
    gallery: [
      "/night-dream/f1.webp",
      "/night-dream/f2.webp",
      "/night-dream/f3.webp",
      "/night-dream/f4.webp",
      "/night-dream/f5.webp",
      "/night-dream/f6.webp"
    ],
    tags: ["Flutter", "SQLite", "Charts", "GetX"],
    github: "https://github.com",
    demo: "https://demo.com",
  },
  {
    id: 3,
    title: "Quiz App",
    description: "Connect with friends, share moments, and discover content. Real-time messaging and notifications.",
    image: "/quiz/cover.webp",
    gallery: [
      "/quiz/f1.webp",
      "/quiz/f2.webp",
      "/quiz/f3.webp",
      "/quiz/f4.webp",
      "/quiz/f5.webp",
      "/quiz/f6.webp",
      "/quiz/f7.webp",
      "/quiz/f8.webp",
    ],
    tags: ["Flutter", "Node.js", "Socket.io", "Bloc"],
    github: "https://github.com",
    demo: "https://demo.com",
  },
  {
    id: 4,
    title: "SCA",
    description: "Beautiful weather forecasts with detailed metrics and location-based alerts. Clean UI design.",
    image: "/sca/cover.webp",
    gallery: [
      "/sca/s1.webp",
      "/sca/s2.webp",
      "/sca/s3.webp",
      "/sca/s4.webp",
      "/sca/s5.webp",
      "/sca/s6.webp",
      "/sca/s7.webp",
      "/sca/s8.webp",
    ],
    tags: ["Flutter", "REST API", "Animations", "Riverpod"],
    github: "https://github.com",
    demo: "https://demo.com",
  }
];