export const projects = [
  {
    id: 1,
    title: "E-Commerce App",
    description: "Full-featured shopping app with cart, payments, and order tracking. Built with Flutter and Firebase.",
    image: "/images/modern-mobile-shopping-app-interface.jpg",
    tags: ["Flutter", "Firebase", "Stripe", "Provider"],
    github: "https://github.com",
    demo: "https://demo.com",
  },
  {
    id: 2,
    title: "Fitness Tracker",
    description: "Track workouts, monitor progress, and achieve fitness goals. Features custom animations and charts.",
    image: "/images/p1.webp",
    tags: ["Flutter", "SQLite", "Charts", "GetX"],
    github: "https://github.com",
    demo: "https://demo.com",
  },
  {
    id: 3,
    title: "Social Media App",
    description: "Connect with friends, share moments, and discover content. Real-time messaging and notifications.",
    image: "/images/social-media-mobile-app-feed.jpg",
    tags: ["Flutter", "Node.js", "Socket.io", "Bloc"],
    github: "https://github.com",
    demo: "https://demo.com",
  },
  {
    id: 4,
    title: "Weather App",
    description: "Beautiful weather forecasts with detailed metrics and location-based alerts. Clean UI design.",
    image: "/images/weather-forecast-mobile-app-interface.jpg",
    tags: ["Flutter", "REST API", "Animations", "Riverpod"],
    github: "https://github.com",
    demo: "https://demo.com",
  },
  {
    id: 5,
    title: "Task Manager",
    description: "Organize tasks, set priorities, and boost productivity. Features drag-and-drop and reminders.",
    image: "/images/task-management-app.png",
    tags: ["Flutter", "Hive", "Notifications", "BLoC"],
    github: "https://github.com",
    demo: "https://demo.com",
  },
  {
    id: 6,
    title: "Recipe App",
    description: "Discover delicious recipes, save favorites, and create shopping lists. Beautiful food photography.",
    image: "/images/recipe-cooking-mobile-app.jpg",
    tags: ["Flutter", "GraphQL", "Caching", "Provider"],
    github: "https://github.com",
    demo: "https://demo.com",
  },
];